---

language: python

python: "3.5"

matrix:
  fast_finish: true
  include:
    - env: BUILD=lint
    - env: BUILD=isort
    - env: BUILD=test

before_install:
  - pip install -IU pip pipenv

install:
  - pipenv install --dev

script:
  - |
    set -ex
    case "$BUILD" in
      isort)
        make sort
        ;;
      lint)
        make lint
        ;;
      test)
        make test
        ;;
    esac
    set +ex

notifications:
  email: false
